import { IProjects } from '../interfaces/IProjects'

export const PROJECTS = [
  {
    id: '6d3dd22e-6c82-4ec1-9154-f87209607e74',
    image: 'https://i.imgur.com/an0gTPC.png',
    title: 'GitHub Blog',
    description: 'Projeto criado como desafio do bootcamp da Rocketseat',
    github: 'https://github.com/rodrigordgfs/Github-Blog',
    link: 'https://github-blog-rose.vercel.app/',
    tags: [
      'React',
      'TypeScript',
      'Context API',
      'Zod',
      'Styled Components',
      'React Hook Forms',
    ],
  },
  {
    id: 'ffacda09-9c43-476d-83ae-4189778c358c',
    image: 'https://i.imgur.com/fXdilpE.png',
    title: 'DT Money',
    description: 'Projeto criado como desafio do bootcamp da Rocketseat',
    github: 'https://github.com/rodrigordgfs/DT-Money',
    link: 'https://dt-money-plum.vercel.app/',
    tags: [
      'React',
      'TypeScript',
      'Context API',
      'Zod',
      'Styled Components',
      'React Hook Forms',
    ],
  },
  {
    id: '02564be7-f41d-410a-8689-f1c0be457b47',
    image: 'https://i.imgur.com/JQlmeoh.png',
    title: 'Coffee Delivery',
    github: 'https://github.com/rodrigordgfs/Coffee-Delivery',
    link: 'https://coffee-delivery-sigma-gules.vercel.app/',
    description: 'Projeto criado como desafio do bootcamp da Rocketseat',
    tags: ['React', 'Styled Components', 'TypeScript', 'Context API'],
  },
  {
    id: '9c2e18fe-aba1-4895-b387-37a271966cdf',
    image: 'https://i.imgur.com/LrJSAcK.png',
    title: 'Ignite Timer',
    description: 'Projeto criado como desafio do bootcamp da Rocketseat',
    github: 'https://github.com/rodrigordgfs/Ignite-Timer',
    link: 'https://ignite-timer-brown-tau.vercel.app/',
    tags: [
      'React',
      'Styled Components',
      'TypeScript',
      'zod',
      'React Hook Forms',
      'date-fns',
    ],
  },
  {
    id: '8114d694-d9aa-40d7-b1b6-37bd092b9a8f',
    image: 'https://i.imgur.com/VxgqCzY.png',
    title: 'R Chat',
    description:
      'Chat criado para colocar em pratica os conhecimentos adiquirido sobre React.',
    github: 'https://github.com/rodrigordgfs/R-Chat',
    link: 'https://r-chat.vercel.app/',
    tags: [
      'React',
      'TailwindCSS',
      'TypeScript',
      'Context API',
      'Firebase',
      'date-fns',
    ],
  },
  {
    id: 'ef4a31f2-d773-4029-bcf8-6c148c91d2d3',
    image: 'https://i.imgur.com/6CG03RE.png',
    title: 'To Do List',
    description: 'Projeto criado como desafio do bootcamp da Rocketseat',
    github: 'https://github.com/rodrigordgfs/ToDo-List',
    link: 'https://to-do-list-pi-tawny.vercel.app/',
    tags: ['React', 'TypeScript', 'CSS Modules', 'Phosphor Icons'],
  },
] as IProjects[]
